set_property SEVERITY {Warning} [get_drc_checks NSTD-1]
set_property SEVERITY {Warning} [get_drc_checks RTSTAT-1]
set_property SEVERITY {Warning} [get_drc_checks UCIO-1]

set_property -dict {PACKAGE_PIN P16 IOSTANDARD LVCMOS33} [get_ports spi_mosi]
set_property -dict {PACKAGE_PIN P18 IOSTANDARD LVCMOS33} [get_ports spi_sclk]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports spi_cs]
set_property -dict {PACKAGE_PIN Y8 IOSTANDARD LVCMOS33} [get_ports vsync]
set_property -dict {PACKAGE_PIN W9 IOSTANDARD LVCMOS33} [get_ports hsync]
set_property -dict {PACKAGE_PIN A20 IOSTANDARD LVCMOS33} [get_ports pclk]
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports rst]
set_property -dict {PACKAGE_PIN Y13 IOSTANDARD LVCMOS33} [get_ports bl_ctr]
set_property -dict {PACKAGE_PIN Y9 IOSTANDARD LVCMOS33} [get_ports DE]
set_property -dict {PACKAGE_PIN W6 IOSTANDARD LVCMOS33} [get_ports {D[0]}]
set_property -dict {PACKAGE_PIN U8 IOSTANDARD LVCMOS33} [get_ports {D[1]}]
set_property -dict {PACKAGE_PIN Y7 IOSTANDARD LVCMOS33} [get_ports {D[2]}]
set_property -dict {PACKAGE_PIN V8 IOSTANDARD LVCMOS33} [get_ports {D[3]}]
set_property -dict {PACKAGE_PIN F20 IOSTANDARD LVCMOS33} [get_ports {D[4]}]
set_property -dict {PACKAGE_PIN V10 IOSTANDARD LVCMOS33} [get_ports {D[5]}]
set_property -dict {PACKAGE_PIN F19 IOSTANDARD LVCMOS33} [get_ports {D[6]}]
set_property -dict {PACKAGE_PIN W10 IOSTANDARD LVCMOS33} [get_ports {D[7]}]
set_property -dict {PACKAGE_PIN U19 IOSTANDARD LVCMOS33} [get_ports {D[8]}]
set_property -dict {PACKAGE_PIN Y16 IOSTANDARD LVCMOS33} [get_ports {D[9]}]
set_property -dict {PACKAGE_PIN Y17 IOSTANDARD LVCMOS33} [get_ports {D[10]}]
set_property -dict {PACKAGE_PIN B20 IOSTANDARD LVCMOS33} [get_ports {D[11]}]
set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVCMOS33} [get_ports {D[12]}]
set_property -dict {PACKAGE_PIN W8 IOSTANDARD LVCMOS33} [get_ports {D[13]}]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports {D[14]}]
set_property -dict {PACKAGE_PIN B19 IOSTANDARD LVCMOS33} [get_ports {D[15]}]
set_property -dict {PACKAGE_PIN U7 IOSTANDARD LVCMOS33} [get_ports {D[16]}]
set_property -dict {PACKAGE_PIN V7 IOSTANDARD LVCMOS33} [get_ports {D[17]}]
set_property -dict {PACKAGE_PIN Y6 IOSTANDARD LVCMOS33} [get_ports {D[18]}]
set_property -dict {PACKAGE_PIN C20 IOSTANDARD LVCMOS33} [get_ports {D[19]}]
set_property -dict {PACKAGE_PIN V6 IOSTANDARD LVCMOS33} [get_ports {D[20]}]
set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS33} [get_ports {D[21]}]
set_property -dict {PACKAGE_PIN W18 IOSTANDARD LVCMOS33} [get_ports {D[22]}]
set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS33} [get_ports {D[23]}]

set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Key[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Key[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Key[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Key[3]}]
set_property PACKAGE_PIN D19 [get_ports {Key[0]}]
set_property PACKAGE_PIN D20 [get_ports {Key[1]}]
set_property PACKAGE_PIN L20 [get_ports {Key[2]}]
set_property PACKAGE_PIN L19 [get_ports {Key[3]}]
set_property PACKAGE_PIN R14 [get_ports {LED[0]}]
set_property PACKAGE_PIN P14 [get_ports {LED[1]}]
set_property PACKAGE_PIN N16 [get_ports {LED[2]}]
set_property PACKAGE_PIN M14 [get_ports {LED[3]}]

